name: "Run Simulator"
description: "Build BSPs for the given target/BSP and run tests on a simulator"

inputs:
  target:
    description: "The Arch/BSP to run. For example 'sparc/erc32'"
    type: string
    required: true
  sources-rtems:
    description: "Where to find the RTEMS sources. Use absolute path!"
    type: string
    required: true
  prefix:
    description: "Prefix directory with the installed tools. Use absolute path!"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - if: ( "${{ inputs.target }}" == "sparc/erc32" )
      shell: bash
      run: |
        # Check whether it's sparc/erc32
        echo "rtems_test_args=--rtems-bsp=erc32-sis" >> $GITHUB_ENV
    - if: ( "${{ env.rtems_test_args }}" == "" )
      shell: bash
      run: |
        # Check whether parameters for this simulator have been found
        echo "${{ inputs.target }} is not supported for simulator runs"
        false
    - shell: bash
      run: |
        # create environment variables for paths and names
        shortname=`echo "${{ inputs.target }}" | sed -e "s|/|_|g"`
        echo "shortname=${shortname}" >> $GITHUB_ENV
        echo "logdir=${GITHUB_WORKSPACE}/logs-${shortname}" >> $GITHUB_ENV
        echo "builddir=${GITHUB_WORKSPACE}/build-${shortname}" >> $GITHUB_ENV
    - shell: bash
      run: |
        # create directories
        mkdir -p "${{ env.logdir }}"
        mkdir -p "${{ env.builddir }}"
    - shell: bash
      run: |
        # generate BSP config
        echo -e "[${{ inputs.target }}]\nBUILD_TESTS = True" >> "${{ env.builddir }}/config.ini"
        cat "${{ env.builddir }}/config.ini"
    - shell: bash
      run: |
        # configure
        cd ${{ env.builddir }} && ${{ inputs.sources-rtems }}/waf configure \
          --out="${{ env.builddir }}" \
          --top="${{ inputs.sources-rtems }}" \
          --prefix="${{ inputs.prefix }}"
    - shell: bash
      run: |
        # compile
        cd ${{ env.builddir }} && ${{ inputs.sources-rtems }}/waf \
          --out="${{ env.builddir }}" \
          --top="${{ inputs.sources-rtems }}" \
          --prefix="${{ inputs.prefix }}"
    - shell: bash
      run: |
        # run tests
        ${{ inputs.prefix }}/bin/rtems-test \
          --log="${{ env.logdir }}/test.log \
          --rtems-tools="${{ inputs.prefix }}" \
          ${{ env.rtems_test_args }}
    - name: Archive log
      uses: actions/upload-artifact@v3
      with:
        name: test-logs-${{ env.shortname }}
        path: logs-${{ env.shortname }}
