name: "Build BSPs"
description: "Build BSPs for the given target architecture."

inputs:
  target:
    description: "The target architecture. For example 'arm'"
    type: string
    required: true
  sources-rtems:
    description: "Where to find the RTEMS sources"
    type: string
    required: true
  prefix:
    description: "prefix directory with the installed tools"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Run BSP builder
      shell: bash
      run: |
        "${{ inputs.prefix }}"/bin/rtems-bsp-builder \
                              --build-path="$HOME/rtems-build" \
                              --rtems-tools="${{ inputs.prefix }}" \
                              --rtems="${{ inputs.sources-rtems }}" \
                              --profiles=everything \
                              --archs=${{ inputs.target }} \
                              --log="$HOME/logs/log-${{ inputs.target }}" \
                              --warnings-report="$HOME/logs/warnings-${{ inputs.target }}" \
                              --failures-report="$HOME/logs/failures-${{ inputs.target }}"
    - name: Archive log
      uses: actions/upload-artifact@v3
      with:
        name: log-${{ inputs.target }}
        path: "$HOME/logs"
