name: "Build BSPs"
description: "Build BSPs for the given target architecture."

inputs:
  target:
    description: "The target architecture. For example 'arm'"
    type: string
    required: true
  sources-rtems:
    description: "Where to find the RTEMS sources. Use absolute path!"
    type: string
    required: true
  prefix:
    description: "Prefix directory with the installed tools. Use absolute path!"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: create log dir
      shell: bash
      run: mkdir "${GITHUB_WORKSPACE}"/bsp-logs
    - name: Run BSP builder
      shell: bash
      run: |
        "${{ inputs.prefix }}"/bin/rtems-bsp-builder \
                              --build-path "${GITHUB_WORKSPACE}"/rtems-build \
                              --prefix "${{ inputs.prefix }}" \
                              --rtems-tools "${{ inputs.prefix }}/bin" \
                              --rtems "${{ inputs.sources-rtems }}" \
                              --profiles tier-1,tier-2 \
                              --arch ${{ inputs.target }} \
                              --log "${GITHUB_WORKSPACE}"/bsp-logs/log-${{ inputs.target }}.txt \
                              --warnings-report "${GITHUB_WORKSPACE}"/bsp-logs/warnings-${{ inputs.target }}.txt \
                              --failures-report "${GITHUB_WORKSPACE}"/bsp-logs/failures-${{ inputs.target }}.txt
    - name: Archive log
      uses: actions/upload-artifact@v3
      with:
        name: log-${{ inputs.target }}
        path: bsp-logs
    - name: Check for errors
      shell: bash
      run: |
        grep "Failures: 0" "$GITHUB_WORKSPACE"/bsp-logs/log-${{ inputs.target }}.txt
