name: "Build BSPs"
description: "Build BSPs for the given target architecture."

inputs:
  target:
    description: "The target architecture. For example 'arm'"
    type: string
    required: true
  sources-rtems:
    description: "Where to find the RTEMS sources"
    type: string
    required: true
  prefix:
    description: "prefix directory with the installed tools"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: create log dir
      shell: bash
      run: mkdir ~/logs
    - name: Run BSP builder
      shell: bash
      run: |
        "${{ inputs.prefix }}"/bin/rtems-bsp-builder \
                              --build-path ~/rtems-build \
                              --prefix "${{ inputs.prefix }}" \
                              --rtems-tools "${{ inputs.prefix }}/bin" \
                              --rtems "${{ inputs.sources-rtems }}" \
                              --profiles everything \
                              --arch ${{ inputs.target }} \
                              --log ~/logs/log-${{ inputs.target }}.txt \
                              --warnings-report ~/logs/warnings-${{ inputs.target }}.txt \
                              --failures-report ~/logs/failures-${{ inputs.target }}.txt
    - name: Archive log
      uses: actions/upload-artifact@v3
      with:
        name: log-${{ inputs.target }}
        path: ~/logs
    - name: Check for errors
      shell: bash
      run: grep "Failures: 0" ~/logs/log-${{ inputs.target }}.txt
